config/routes.rb
Rails.application.routes.draw do
  root 'matches#new'

  devise_for :users, class_name: 'RealUser', :controllers => {:registrations => "registrations"}
  resources :matches, except: [:edit, :destroy]

  get '/participations' => 'participations#index'

  get '/api/authenticate' => 'api#authenticate'
  post '/api/authenticate' => 'api#authenticate'
  get '/api/matches/new' => 'api#new'
  post '/api/matches' => 'api#create'
  patch '/api/matches/:id' => 'api#update'
  put '/api/matches/:id' => 'api#update'
  get '/api/matches/:id' => 'api#show'

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :participations
  has_many :users, :through => :participations
  belongs_to :winner, class_name: 'User', foreign_key: 'winner_id'
  serialize :game
  after_create :set_defaults, :save

  FIRST_PROMPT = ", click card, player and me to request cards!"

  def set_defaults
    self.game ||= Game.new(players: self.users.map { |user| Player.new(name: user.name, id: user.id) }, hand_size: self.hand_size)
    self.game.next_turn = self.game.players.find { |player| user(player).is_a? RealUser } if game.requests.length == 0
    self.message ||= game.next_turn.name + FIRST_PROMPT
  end

  def notify_observers
    match_client_notifier.send_notice(self)
  end

  def match_client_notifier
    @match_client_notifier ||= MatchClientNotifier.new
  end

  def players
    game.players
  end

  def user(player)
    User.find_by_id(player.id)
  end

  def player(user)
    players.find { |player| player.id == user.id }
  end

  def opponents(player)
    players.clone.tap { |players| players.rotate!(players.index{ |available_player| available_player.id == player.id}).shift }
  end

  def view(user)
    player = player(user)
    return {
      message: self.message,
      player: player,
      player_index: players.index(player),
      opponents: opponents(player).map { |opponent| {id: opponent.id, name: opponent.name, icon: opponent.icon} },
      scores: players.map { |player| [player.name, player.books.size] }.push(["Fish Left", game.deck.count_cards])
    }.to_json
  end

  def run_play(player, opponent, rank) # would belong in a controller in a rails app
    if game.next_turn.id == player.id
      execute_turn(player, opponent, rank)
      save
      notify_observers
      next_user = user(game.next_turn)
      next_user.make_play(self) if next_user.is_a?(RobotUser) && !game.game_over?
    end
  end

  def execute_turn(player, opponent, rank)
    rank == "six" ? rank_word = "sixe" : rank_word = rank
    self.message = "#{player.name} asked #{opponent.name} for #{rank_word}s and"
    if game.make_request(player, opponent, rank).won_cards?
      self.message += " got cards"
    else
      self.message += " went fish"
      self.message += " and got one" if rank == game.go_fish(player, rank).rank
    end
    if game.game_over?
      end_match
      self.message += "! Game over! Winner: #{game.winner.name}"
    else
      self.message += "! It's #{game.next_turn.name}'s turn!"
    end
  end

  def end_match
    self.winner = user(game.winner)
    participations.where(user: winner).each {|participation| participation.update_attribute(:points, 1)}
    update_column(:over, true)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_match, only: [:show, :update]

  Pusher.url = "https://39cc3ae7664f69e97e12:60bb9ff467a643cc4001@api.pusherapp.com/apps/151900"

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/new
  def new
    @match = Match.new
    @player_range = Game::PLAYER_RANGE
  end

  # POST /matches
  # POST /matches.json
  def create
    match_maker.match(current_user, params["num_players"].to_i)
    Thread.start { start_match(5) }
    respond_to do |format|
      format.json { render_success }
      format.js {}
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    opponent = @match.player(User.find(params["opponentUserId"].to_i))
    @match.run_play(@match.player(current_user), opponent, params["rank"])
    render_success
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @player = @match.player(current_user) if @match
    respond_to do |format|
      format.html { @player ? (render :show) : (render :no_show) }
      format.json { @player ? (render json: @match.view(current_user)) : (render json: { error: 'unauthorized match' }, status: :unauthorized) }
    end
  end

  def match_maker
    @@match_maker ||= MatchMaker.new
  end

  def start_match(seconds)
    match = match_maker.start_match_thread(current_user, seconds)
    push(match) if match
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    def push(match)
      match.users.each do |user|
        Pusher.trigger("waiting_for_players_channel_#{user.id}", 'send_to_game_event', { message: "#{match.id}" } )
      end
    end

    def render_success
      render json: {}, status: :ok
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.slim
= form_for @match, remote:true do |f|
  - if @match.errors.any?
    #error_explanation
      p = "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      ul
        - @match.errors.full_messages.each do |message|
          li = message

  = f.label 'Number of Players'
  br
  ul class='radio-buttons' id='radio_buttons'
    - @player_range.each do |num_players|
      li: input required=true type='radio' id="#{num_players}" value="#{num_players}" name='num_players'
        label for="#{num_players}" #{num_players}
  br
  .actions = f.submit

app/views/matches/create.js.erb
console.log("create.js.erb file called");
document.getElementById('create_pond').innerText = 'Waiting for players';
document.getElementById('new_match').innerHTML = "<h1>Game Requested</h1>";

app/views/matches/index.html.slim
h1 Listing matches

table
  thead
    tr
      th Over
      th Message
      th Hand size
      th Game

  tbody
    - @matches.each do |match|
      tr
        td = match.over
        td = match.message
        td = match.hand_size
        td = match.game
        td = link_to 'Show', match

br

= link_to 'New Match', new_match_path

app/views/matches/new.html.slim
div id="data-marker" data-page="matches/new" data-user_id=current_user.id
br
div class="pond"
  div id="speech"
    div id="message"
      h2 id="create_pond" Create your pond!
  div id="fish_blue"
br
  
div class="form"
  == render 'form'
br

app/views/matches/no_show.slim
div id="data-marker" data-page="game/no_show"
div id="no_player_message"
  h2 "Whoa! That player has been fed to the fish!"

app/views/matches/show.html.slim
div id="data-marker" data-page="matches/show"
div class="opponents" id="opponents"
div class="pond"
  div id="speech"
    div id="message"
  div id="fish_blue"
div class="info-for-player"
  div class="score" id="books"
    h4 Your Books
  div class="player" id="player"
  div class="score" id="score_header"
    h4 Score
    div class="score" id="scores"